import "server-only";
import type { FindingRow, UserSettingsRow } from "@/types/database";
import { getPublicAppUrl } from "@/lib/utils/constants";
import { safeErrorMessage } from "@/lib/utils/errors";
import { countSeverities, getRiskLevel } from "@/lib/utils/scoring";
import { severityRank } from "@/lib/utils/formatting";

interface GitHubCommentClient {
  request: (
    route:
      | "POST /repos/{owner}/{repo}/issues/{issue_number}/comments"
      | "POST /repos/{owner}/{repo}/pulls/{pull_number}/comments",
    parameters: Record<string, unknown>
  ) => Promise<{ data: unknown }>;
}

interface PostReviewCommentsInput {
  owner: string;
  repo: string;
  pullNumber: number;
  commitSha: string;
  reviewId: string;
  reviewUrl?: string | null;
  summary: string;
  riskScore: number;
  shouldBlockMerge: boolean;
  findings: FindingRow[];
  largeDiffLimited: boolean;
  settings: UserSettingsRow;
}

function mergeRecommendation(input: { shouldBlockMerge: boolean; riskScore: number }) {
  if (input.shouldBlockMerge) return "Review required before merging";
  if (input.riskScore >= 31) return "Review recommended before merging";
  return "No blocking issues detected";
}

function fullReportUrl(reviewId: string) {
  return `${getPublicAppUrl()}/reviews/${reviewId}`;
}

export function buildSummaryComment(input: PostReviewCommentsInput) {
  const counts = countSeverities(input.findings);
  const topIssues = input.findings
    .slice()
    .sort((a, b) => severityRank(b.severity) - severityRank(a.severity))
    .slice(0, 5)
    .map((finding, index) => `${index + 1}. ${finding.title} in \`${finding.file_path || "unknown file"}\``)
    .join("\n");

  const limitation = input.largeDiffLimited
    ? "\n\n> Large diff note: PR Sentinel AI prioritized the most important files because the configured diff limit was reached."
    : "";

  return `## PR Sentinel AI Review Complete

**Risk Score:** ${input.riskScore}/100 (${getRiskLevel(input.riskScore)})  
**Merge Recommendation:** ${mergeRecommendation(input)}

### Findings Summary
- Critical: ${counts.critical}
- High: ${counts.high}
- Medium: ${counts.medium}
- Low: ${counts.low}

### Top Issues
${topIssues || "No actionable findings detected."}

### Overall Summary
${input.summary}${limitation}

### Full Report
${fullReportUrl(input.reviewId)}

Generated by PR Sentinel AI.`;
}

function buildInlineBody(finding: FindingRow) {
  const severity = finding.severity.charAt(0).toUpperCase() + finding.severity.slice(1);
  const category = finding.category.replace("_", " ");
  const code = finding.suggested_code ? `\n\n\`\`\`ts\n${finding.suggested_code}\n\`\`\`` : "";

  return `## ${severity} ${category} Issue: ${finding.title}

${finding.explanation || ""}

### Why it matters
${finding.why_it_matters || ""}

### Suggested fix
${finding.suggested_fix || ""}${code}`;
}

function getCommentId(response: { data: unknown }) {
  if (typeof response.data === "object" && response.data && "id" in response.data) {
    const id = (response.data as { id?: unknown }).id;
    return typeof id === "number" ? id : null;
  }
  return null;
}

async function createIssueComment(
  octokit: GitHubCommentClient,
  input: { owner: string; repo: string; issueNumber: number; body: string }
) {
  const response = await octokit.request("POST /repos/{owner}/{repo}/issues/{issue_number}/comments", {
    owner: input.owner,
    repo: input.repo,
    issue_number: input.issueNumber,
    body: input.body
  });

  return getCommentId(response);
}

async function createPullRequestReviewComment(
  octokit: GitHubCommentClient,
  input: {
    owner: string;
    repo: string;
    pullNumber: number;
    body: string;
    commitId: string;
    path: string;
    line: number;
  }
) {
  const response = await octokit.request("POST /repos/{owner}/{repo}/pulls/{pull_number}/comments", {
    owner: input.owner,
    repo: input.repo,
    pull_number: input.pullNumber,
    body: input.body,
    commit_id: input.commitId,
    path: input.path,
    line: input.line,
    side: "RIGHT"
  });

  return getCommentId(response);
}

export async function postReviewComments(octokit: GitHubCommentClient, input: PostReviewCommentsInput) {
  const inlineComments: Array<{ findingId: string; commentId: number }> = [];
  const failedInline: FindingRow[] = [];
  const commentFailures: string[] = [];
  let summaryCommentPosted = false;

  if (input.settings.post_summary_comment !== false) {
    try {
      await createIssueComment(octokit, {
        owner: input.owner,
        repo: input.repo,
        issueNumber: input.pullNumber,
        body: buildSummaryComment(input)
      });
      summaryCommentPosted = true;
    } catch (error) {
      commentFailures.push(`Summary comment failed: ${safeErrorMessage(error, "GitHub rejected the summary comment.")}`);
    }
  }

  if (input.settings.post_inline_comments !== false) {
    const minSeverity = input.settings.minimum_inline_severity || "medium";
    const limit = input.settings.max_inline_comments || 10;
    const candidates = input.findings
      .filter((finding) => finding.file_path && finding.line_number)
      .filter((finding) => severityRank(finding.severity) >= severityRank(minSeverity))
      .sort((a, b) => severityRank(b.severity) - severityRank(a.severity))
      .slice(0, limit);

    for (const finding of candidates) {
      try {
        const commentId = await createPullRequestReviewComment(octokit, {
          owner: input.owner,
          repo: input.repo,
          pullNumber: input.pullNumber,
          commitId: input.commitSha,
          path: finding.file_path || "",
          line: finding.line_number || 1,
          body: buildInlineBody(finding)
        });
        if (commentId) {
          inlineComments.push({ findingId: finding.id, commentId });
        } else {
          failedInline.push(finding);
          commentFailures.push(`Inline comment returned no comment id for finding ${finding.id}.`);
        }
      } catch (error) {
        failedInline.push(finding);
        commentFailures.push(
          `Inline comment failed for ${finding.file_path || "unknown file"}${
            finding.line_number ? `:${finding.line_number}` : ""
          }: ${safeErrorMessage(error, "GitHub rejected the inline comment.")}`
        );
      }
    }
  }

  if (failedInline.length > 0) {
    const fallback = failedInline
      .map(
        (finding) =>
          `- **${finding.severity.toUpperCase()}** ${finding.title} in \`${finding.file_path}\`${finding.line_number ? `:${finding.line_number}` : ""}`
      )
      .join("\n");

    try {
      await createIssueComment(octokit, {
        owner: input.owner,
        repo: input.repo,
        issueNumber: input.pullNumber,
        body: `## PR Sentinel AI Inline Comment Fallback

GitHub rejected one or more inline comments, so PR Sentinel AI is grouping them here:

${fallback}

Full report: ${fullReportUrl(input.reviewId)}`
      });
    } catch (error) {
      commentFailures.push(`Inline fallback comment failed: ${safeErrorMessage(error, "GitHub rejected the fallback comment.")}`);
    }
  }

  return {
    inlineComments,
    failedInlineCount: failedInline.length,
    summaryCommentPosted,
    commentFailures
  };
}
