import "server-only";
import type { Octokit } from "@octokit/rest";
import type { FindingRow, UserSettingsRow } from "@/types/database";
import { getPublicAppUrl } from "@/lib/utils/constants";
import { countSeverities, getRiskLevel } from "@/lib/utils/scoring";
import { severityRank } from "@/lib/utils/formatting";

interface PostReviewCommentsInput {
  owner: string;
  repo: string;
  pullNumber: number;
  commitSha: string;
  reviewId: string;
  reviewUrl?: string | null;
  summary: string;
  riskScore: number;
  shouldBlockMerge: boolean;
  findings: FindingRow[];
  largeDiffLimited: boolean;
  settings: UserSettingsRow;
}

function mergeRecommendation(input: { shouldBlockMerge: boolean; riskScore: number }) {
  if (input.shouldBlockMerge) return "Review required before merging";
  if (input.riskScore >= 31) return "Review recommended before merging";
  return "No blocking issues detected";
}

function fullReportUrl(reviewId: string) {
  return `${getPublicAppUrl()}/reviews/${reviewId}`;
}

export function buildSummaryComment(input: PostReviewCommentsInput) {
  const counts = countSeverities(input.findings);
  const topIssues = input.findings
    .slice()
    .sort((a, b) => severityRank(b.severity) - severityRank(a.severity))
    .slice(0, 5)
    .map((finding, index) => `${index + 1}. ${finding.title} in \`${finding.file_path || "unknown file"}\``)
    .join("\n");

  const limitation = input.largeDiffLimited
    ? "\n\n> Large diff note: PR Sentinel AI prioritized the most important files because the configured diff limit was reached."
    : "";

  return `## PR Sentinel AI Review Complete

**Risk Score:** ${input.riskScore}/100 (${getRiskLevel(input.riskScore)})  
**Merge Recommendation:** ${mergeRecommendation(input)}

### Findings Summary
- Critical: ${counts.critical}
- High: ${counts.high}
- Medium: ${counts.medium}
- Low: ${counts.low}

### Top Issues
${topIssues || "No actionable findings detected."}

### Overall Summary
${input.summary}${limitation}

### Full Report
${fullReportUrl(input.reviewId)}

Generated by PR Sentinel AI.`;
}

function buildInlineBody(finding: FindingRow) {
  const severity = finding.severity.charAt(0).toUpperCase() + finding.severity.slice(1);
  const category = finding.category.replace("_", " ");
  const code = finding.suggested_code ? `\n\n\`\`\`ts\n${finding.suggested_code}\n\`\`\`` : "";

  return `## ${severity} ${category} Issue: ${finding.title}

${finding.explanation || ""}

### Why it matters
${finding.why_it_matters || ""}

### Suggested fix
${finding.suggested_fix || ""}${code}`;
}

export async function postReviewComments(octokit: Octokit, input: PostReviewCommentsInput) {
  const inlineComments: Array<{ findingId: string; commentId: number }> = [];
  const failedInline: FindingRow[] = [];

  if (input.settings.post_summary_comment !== false) {
    await octokit.issues.createComment({
      owner: input.owner,
      repo: input.repo,
      issue_number: input.pullNumber,
      body: buildSummaryComment(input)
    });
  }

  if (input.settings.post_inline_comments !== false) {
    const minSeverity = input.settings.minimum_inline_severity || "medium";
    const limit = input.settings.max_inline_comments || 10;
    const candidates = input.findings
      .filter((finding) => finding.file_path && finding.line_number)
      .filter((finding) => severityRank(finding.severity) >= severityRank(minSeverity))
      .sort((a, b) => severityRank(b.severity) - severityRank(a.severity))
      .slice(0, limit);

    for (const finding of candidates) {
      try {
        const response = await octokit.pulls.createReviewComment({
          owner: input.owner,
          repo: input.repo,
          pull_number: input.pullNumber,
          commit_id: input.commitSha,
          path: finding.file_path || "",
          line: finding.line_number || 1,
          side: "RIGHT",
          body: buildInlineBody(finding)
        });
        inlineComments.push({ findingId: finding.id, commentId: response.data.id });
      } catch {
        failedInline.push(finding);
      }
    }
  }

  if (failedInline.length > 0) {
    const fallback = failedInline
      .map(
        (finding) =>
          `- **${finding.severity.toUpperCase()}** ${finding.title} in \`${finding.file_path}\`${finding.line_number ? `:${finding.line_number}` : ""}`
      )
      .join("\n");

    await octokit.issues.createComment({
      owner: input.owner,
      repo: input.repo,
      issue_number: input.pullNumber,
      body: `## PR Sentinel AI Inline Comment Fallback

GitHub rejected one or more inline comments, so PR Sentinel AI is grouping them here:

${fallback}

Full report: ${fullReportUrl(input.reviewId)}`
    });
  }

  return { inlineComments, failedInlineCount: failedInline.length };
}
